<%@ page language="java" contentType="text/html; charset=EUC-KR"
    pageEncoding="EUC-KR"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=EUC-KR">
<title>Insert title here</title>
<style type="text/css">
td{
	color: white;
}
</style>
</head>
<body>
	<center>
	 	<table>

		   	<tr border=1 bgcolor=#999>

		    	<th>메뉴명</th>
		    	<th>중량(g/ml)</th>
		    	<th>열량(kcal)</th>
		    	<th>당(g)</th>
		    	<th>단백질(g)</th>
		    	<th>포화지방(g)</th>
		    	<th>나트륨(mg)</th>
		    </tr>
		    <tr>
		    	<td>브리오쉬번</td>
		    	<td>55g</td>
		    	<td>180</td>
		    	<td>4</td>
		    	<td>5(9%)</td>
		    	<td>2.1(14%)</td>
		    	<td>160(8g)</td>
		    </tr>
		    <tr>
		    	<td>오트밀번</td>
		    	<td>55g</td>
		    	<td>190</td>
		    	<td>4</td>
		    	<td>6(11%)</td>
		    	<td>2.1(14%)</td>
		    	<td>170(9%)</td>
		    </tr>
		    <tr>
		    	<td>레터스랩</td>
		    	<td>40g</td>
		    	<td>12</td>
		    	<td>0</td>
		    	<td>1(11%)</td>
		    	<td>0(0%)</td>
		    	<td>64(3%)</td>
		    </tr>
		    <tr>
		    	<td>100% 앵거스비프패티</td>
		    	<td>81g</td>
		    	<td>229</td>
		    	<td>0</td>
		    	<td>17(31%)</td>
		    	<td>7.0(47%)</td>
		    	<td>112(6%)</td>
		    </tr>
		    <tr>
		    	<td>메이플베이컨</td>
		    	<td>12g</td>
		    	<td>55</td>
		    	<td>0</td>
		    	<td>4(7%)</td>
		    	<td>1.5(10%)</td>
		    	<td>107(5%)</td>
		    </tr>
		    <tr>
		    	<td>아메리칸치즈</td>
		    	<td>14g</td>
		    	<td>49</td>
		    	<td>0</td>
		    	<td>3(5%)</td>
		    	<td>2.8(18%)</td>
		    	<td>210(11%)</td>
		    </tr>
		    <tr>
		    	<td>프로볼로네치즈</td>
		    	<td>14g</td>
		    	<td>50</td>
		    	<td>0</td>
		    	<td>4(7%)</td>
		    	<td>2.2(15%)</td>
		    	<td>122(6%)</td>
		    </tr>
		    <tr>
		    	<td>페퍼잭치즈</td>
		    	<td>14g</td>
		    	<td>52</td>
		    	<td>0</td>
		    	<td>3(6%)</td>
		    	<td>2.6(17%)</td>
		    	<td>94(5%)</td>
		    </tr>
		    <tr>
		    	<td>마요네즈</td>
		    	<td>10g</td>
		    	<td>38</td>
		    	<td>0</td>
		    	<td>0(0%)</td>
		    	<td>0.6(4%)</td>
		    	<td>63(3%)</td>
		    </tr>
		    <tr>
		    	<td>빅맥스폐셜소스</td>
		    	<td>10g</td>
		    	<td>30</td>
		    	<td>1</td>
		    	<td>0(0%)</td>
		    	<td>0.4(3%)</td>
		    	<td>58(3%)</td>
		    </tr>
		    <tr>
		    	<td>머스타드</td>
		    	<td>5g</td>
		    	<td>3</td>
		    	<td>0</td>
		    	<td>0(0%)</td>
		    	<td>0(0%)</td>
		    	<td>56(3%)</td>
		    </tr>
		    <tr>
		    	<td>토마토할라피뇨렐리시소스</td>
		    	<td>15g</td>
		    	<td>18</td>
		    	<td>3</td>
		    	<td>0(1%)</td>
		    	<td>1.0(7%)</td>
		    	<td>61(3%)</td>
		    </tr>
		     <tr>
		    	<td>아이올리소스</td>
		    	<td>10g</td>
		    	<td>37</td>
		    	<td>1</td>
		    	<td>0(0%)</td>
		    	<td>0(0%)</td>
		    	<td>85(4%)</td>
		    </tr>
		    <tr>
		    	<td>발사믹소스</td>
		    	<td>10g</td>
		    	<td>21</td>
		    	<td>2</td>
		    	<td>0(0%)</td>
		    	<td>0(0%)</td>
		    	<td>3(0%)</td>
		    </tr>
		    <tr>
		    	<td>케첩소스</td>
		    	<td>10g</td>
		    	<td>11</td>
		    	<td>2</td>
		    	<td>0(0%)</td>
		    	<td>0(0%)</td>
		    	<td>92(5%)</td>
		    </tr>
		    <tr>
		    	<td>스파이시바비큐소스</td>
		    	<td>10g</td>
		    	<td>15</td>
		    	<td>3</td>
		    	<td>0(0%)</td>
		    	<td>0(0%)</td>
		    	<td>78(4%)</td>
		    </tr>
		    <tr>
		    	<td>롱슬라이스피클</td>
		    	<td>16g</td>
		    	<td>1</td>
		    	<td>0</td>
		    	<td>0(0%)</td>
		    	<td>0(0%)</td>
		    	<td>106(5%)</td>
		    </tr>
		    <tr>
		    	<td>토마토</td>
		    	<td>37g</td>
		    	<td>5</td>
		    	<td>1</td>
		    	<td>0(1%)</td>
		    	<td>0(0%)</td>
		    	<td>7(0%)</td>
		    </tr>
		    <tr>
		    	<td>어니언</td>
		    	<td>7g</td>
		    	<td>2</td>
		    	<td>0</td>
		    	<td>0(0%)</td>
		    	<td>0(0%)</td>
		    	<td>0(0%)</td>
		    </tr>
		    <tr>
		    	<td>레드어니언</td>
		    	<td>15g</td>
		    	<td>5</td>
		    	<td>1</td>
		    	<td>0(0%)</td>
		    	<td>0(0%)</td>
		    	<td>1(0%)</td>
		    </tr>
		    <tr>
		    	<td>레터스</td>
		    	<td>10g</td>
		    	<td>3</td>
		    	<td>0</td>
		    	<td>0(0%)</td>
		    	<td>0(0%)</td>
		    	<td>16(1%)</td>
		    </tr>
		    <tr>
		    	<td>할라피뇨</td>
		    	<td>22g</td>
		    	<td>12</td>
		    	<td>3</td>
		    	<td>0(0%)</td>
		    	<td>0(0%)</td>
		    	<td>148(7%)</td>
		    </tr>
		    <tr>
		    	<td>그릴드어니언</td>
		    	<td>15g</td>
		    	<td>9</td>
		    	<td>1</td>
		    	<td>0(0%)</td>
		    	<td>0.1(1%)</td>
		    	<td>51(3%)</td>
		    </tr>
		    <tr>
		    	<td>그릴드머쉬룸</td>
		    	<td>15g</td>
		    	<td>8</td>
		    	<td>0</td>
		    	<td>1(1%)</td>
		    	<td>0(0%)</td>
		    	<td>11(1%)</td>
		    </tr>
		    <tr>
		    	<td>피클(사이드)</td>
		    	<td>30g</td>
		    	<td>20</td>
		    	<td>5</td>
		    	<td>0(0%)</td>
		    	<td>0(0%)</td>
		    	<td>46(2%)</td>
		    </tr>
		    <tr>
		    	<td>케첩(2개)</td>
		    	<td>18g</td>
		    	<td>20</td>
		    	<td>4</td>
		    	<td>0(1%)</td>
		    	<td>0(0%)</td>
		    	<td>146(7%)</td>
		    </tr>
   		</table>
	</center>
</body>
</html>